//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internationalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Internationalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a test task. 的本地化字符串。
        /// </summary>
        public static string AboutInfo {
            get {
                return ResourceManager.GetString("AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About this task 的本地化字符串。
        /// </summary>
        public static string AboutTask {
            get {
                return ResourceManager.GetString("AboutTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Type 的本地化字符串。
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address2 的本地化字符串。
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address required. 的本地化字符串。
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin Support 的本地化字符串。
        /// </summary>
        public static string AdminSupport {
            get {
                return ResourceManager.GetString("AdminSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advertising 的本地化字符串。
        /// </summary>
        public static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Development 的本地化字符串。
        /// </summary>
        public static string ApplicationDevelopment {
            get {
                return ResourceManager.GetString("ApplicationDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Area Code 的本地化字符串。
        /// </summary>
        public static string AreaCode {
            get {
                return ResourceManager.GetString("AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Article Writing 的本地化字符串。
        /// </summary>
        public static string ArticleWriting {
            get {
                return ResourceManager.GetString("ArticleWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;&lt; Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basics Information 的本地化字符串。
        /// </summary>
        public static string BasicsInfo {
            get {
                return ResourceManager.GetString("BasicsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blog 的本地化字符串。
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Business 的本地化字符串。
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username exists, please try a different username. 的本地化字符串。
        /// </summary>
        public static string CheckUser {
            get {
                return ResourceManager.GetString("CheckUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please chose the file! 的本地化字符串。
        /// </summary>
        public static string ChoseFile {
            get {
                return ResourceManager.GetString("ChoseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 City 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Name(optional) 的本地化字符串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conference 的本地化字符串。
        /// </summary>
        public static string Conference {
            get {
                return ResourceManager.GetString("Conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue &gt;&gt; 的本地化字符串。
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country 的本地化字符串。
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 International Area Code 的本地化字符串。
        /// </summary>
        public static string CountryPhone {
            get {
                return ResourceManager.GetString("CountryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coworker 的本地化字符串。
        /// </summary>
        public static string Coworker {
            get {
                return ResourceManager.GetString("Coworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create an Account 的本地化字符串。
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello and welcome to Demo! Already have an account? 的本地化字符串。
        /// </summary>
        public static string CreateAccountInfo {
            get {
                return ResourceManager.GetString("CreateAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Basics Informations 的本地化字符串。
        /// </summary>
        public static string CreateBasics {
            get {
                return ResourceManager.GetString("CreateBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Your Profile Started! 的本地化字符串。
        /// </summary>
        public static string CreateBasicsInfo1 {
            get {
                return ResourceManager.GetString("CreateBasicsInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First, let&apos;s get some basics out of the way... 的本地化字符串。
        /// </summary>
        public static string CreateBasicsInfo2 {
            get {
                return ResourceManager.GetString("CreateBasicsInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Employer Informations 的本地化字符串。
        /// </summary>
        public static string CreateEmployer {
            get {
                return ResourceManager.GetString("CreateEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Skills Informations 的本地化字符串。
        /// </summary>
        public static string CreateSkills {
            get {
                return ResourceManager.GetString("CreateSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Your Profile Started! 的本地化字符串。
        /// </summary>
        public static string CreateSkillsInfo1 {
            get {
                return ResourceManager.GetString("CreateSkillsInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Market your skills and experience... 的本地化字符串。
        /// </summary>
        public static string CreateSkillsInfo2 {
            get {
                return ResourceManager.GetString("CreateSkillsInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Worker 的本地化字符串。
        /// </summary>
        public static string CreateWorker {
            get {
                return ResourceManager.GetString("CreateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a Contractor Account 的本地化字符串。
        /// </summary>
        public static string CreateWorkerInfo1 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looking to hire? 的本地化字符串。
        /// </summary>
        public static string CreateWorkerInfo2 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Employer Information 的本地化字符串。
        /// </summary>
        public static string CreateWorkerInfo3 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How do you want to represent yourself to clients on task publish system? 的本地化字符串。
        /// </summary>
        public static string CreateWorkerInfo4 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Entry 的本地化字符串。
        /// </summary>
        public static string DataEntry {
            get {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design&amp;Multimedia 的本地化字符串。
        /// </summary>
        public static string DesignMultimedia {
            get {
                return ResourceManager.GetString("DesignMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Name 的本地化字符串。
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-books and Blogs 的本地化字符串。
        /// </summary>
        public static string EbooksBlogs {
            get {
                return ResourceManager.GetString("EbooksBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail Address 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail address is not correct. 的本地化字符串。
        /// </summary>
        public static string EmailFaield {
            get {
                return ResourceManager.GetString("EmailFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail Address required. 的本地化字符串。
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Employer Information 的本地化字符串。
        /// </summary>
        public static string EmployerInfo {
            get {
                return ResourceManager.GetString("EmployerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Employer Profile 的本地化字符串。
        /// </summary>
        public static string EmployerProfile {
            get {
                return ResourceManager.GetString("EmployerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ext 的本地化字符串。
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Facebook 的本地化字符串。
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Name 的本地化字符串。
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First name required. 的本地化字符串。
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friend 的本地化字符串。
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphic Design 的本地化字符串。
        /// </summary>
        public static string GraphicDesign {
            get {
                return ResourceManager.GetString("GraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My hourly rate 的本地化字符串。
        /// </summary>
        public static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field must be a number 的本地化字符串。
        /// </summary>
        public static string HourlyRateFailed {
            get {
                return ResourceManager.GetString("HourlyRateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My hourly rate required. 的本地化字符串。
        /// </summary>
        public static string HourlyRateRequired {
            get {
                return ResourceManager.GetString("HourlyRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How did you hear about us? 的本地化字符串。
        /// </summary>
        public static string How {
            get {
                return ResourceManager.GetString("How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Illustration 的本地化字符串。
        /// </summary>
        public static string Illustration {
            get {
                return ResourceManager.GetString("Illustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Individual 的本地化字符串。
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IT&amp;Programming 的本地化字符串。
        /// </summary>
        public static string ITProgramming {
            get {
                return ResourceManager.GetString("ITProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Name 的本地化字符串。
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last name required. 的本地化字符串。
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lead Generation 的本地化字符串。
        /// </summary>
        public static string LeadGeneration {
            get {
                return ResourceManager.GetString("LeadGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linkedln 的本地化字符串。
        /// </summary>
        public static string Linkedln {
            get {
                return ResourceManager.GetString("Linkedln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed, please check the username and password. 的本地化字符串。
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input username and password. if you do not have an account, please 的本地化字符串。
        /// </summary>
        public static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log off 的本地化字符串。
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logos 的本地化字符串。
        /// </summary>
        public static string Logos {
            get {
                return ResourceManager.GetString("Logos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile Apps 的本地化字符串。
        /// </summary>
        public static string MobileApps {
            get {
                return ResourceManager.GetString("MobileApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online advertisement 的本地化字符串。
        /// </summary>
        public static string OnlineAdvertisement {
            get {
                return ResourceManager.GetString("OnlineAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online news article 的本地化字符串。
        /// </summary>
        public static string OnlineNewsArticle {
            get {
                return ResourceManager.GetString("OnlineNewsArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        public static string OverView {
            get {
                return ResourceManager.GetString("OverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview required. 的本地化字符串。
        /// </summary>
        public static string OverViewRequired {
            get {
                return ResourceManager.GetString("OverViewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your passwords do not match. 的本地化字符串。
        /// </summary>
        public static string PassWordFaield {
            get {
                return ResourceManager.GetString("PassWordFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is required. 的本地化字符串。
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone Number 的本地化字符串。
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field must be a phone number 的本地化字符串。
        /// </summary>
        public static string PhoneNumberField {
            get {
                return ResourceManager.GetString("PhoneNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Picture(optional) 的本地化字符串。
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post a Job 的本地化字符串。
        /// </summary>
        public static string PostJob {
            get {
                return ResourceManager.GetString("PostJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile 的本地化字符串。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 register 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register as a client 的本地化字符串。
        /// </summary>
        public static string RegisterEmployer {
            get {
                return ResourceManager.GetString("RegisterEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relemarketing 的本地化字符串。
        /// </summary>
        public static string Relemarketing {
            get {
                return ResourceManager.GetString("Relemarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Research 的本地化字符串。
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resend verification email 的本地化字符串。
        /// </summary>
        public static string ResendEmail {
            get {
                return ResourceManager.GetString("ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retype Password 的本地化字符串。
        /// </summary>
        public static string RetypePassWord {
            get {
                return ResourceManager.GetString("RetypePassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retype Password required. 的本地化字符串。
        /// </summary>
        public static string RetypePassWordRequired {
            get {
                return ResourceManager.GetString("RetypePassWordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sales&amp;Marketing 的本地化字符串。
        /// </summary>
        public static string SalesMarketing {
            get {
                return ResourceManager.GetString("SalesMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search&amp;Online Marketing 的本地化字符串。
        /// </summary>
        public static string SearchOnlineMarketing {
            get {
                return ResourceManager.GetString("SearchOnlineMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --Select-- 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select all 的本地化字符串。
        /// </summary>
        public static string SelectALL {
            get {
                return ResourceManager.GetString("SelectALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Email 的本地化字符串。
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Task publish system! 的本地化字符串。
        /// </summary>
        public static string SendEmailBody {
            get {
                return ResourceManager.GetString("SendEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, error happened, please wait! 的本地化字符串。
        /// </summary>
        public static string SendEmailFaield {
            get {
                return ResourceManager.GetString("SendEmailFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please verify your E-mail address. 的本地化字符串。
        /// </summary>
        public static string SendEmailSubject {
            get {
                return ResourceManager.GetString("SendEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We are already send a E-mail to you, please check it and verify your E-mail address. 的本地化字符串。
        /// </summary>
        public static string SendEmailSuccess {
            get {
                return ResourceManager.GetString("SendEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills 的本地化字符串。
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills and Experience 的本地化字符串。
        /// </summary>
        public static string SkillsExperience {
            get {
                return ResourceManager.GetString("SkillsExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills required. 的本地化字符串。
        /// </summary>
        public static string SkillsRequired {
            get {
                return ResourceManager.GetString("SkillsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Social Media Site 的本地化字符串。
        /// </summary>
        public static string SocialMediaSite {
            get {
                return ResourceManager.GetString("SocialMediaSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Your Profile 的本地化字符串。
        /// </summary>
        public static string StartProfile {
            get {
                return ResourceManager.GetString("StartProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State/Province 的本地化字符串。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What system will change clients(after system fees) 的本地化字符串。
        /// </summary>
        public static string SystemRate {
            get {
                return ResourceManager.GetString("SystemRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field must be a number 的本地化字符串。
        /// </summary>
        public static string SystemRateFailed {
            get {
                return ResourceManager.GetString("SystemRateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Rate required. 的本地化字符串。
        /// </summary>
        public static string SystemRateRequired {
            get {
                return ResourceManager.GetString("SystemRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tasks publish system 的本地化字符串。
        /// </summary>
        public static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tagline(optional) 的本地化字符串。
        /// </summary>
        public static string Tagline {
            get {
                return ResourceManager.GetString("Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transcription 的本地化字符串。
        /// </summary>
        public static string Transcription {
            get {
                return ResourceManager.GetString("Transcription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation 的本地化字符串。
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TV/Radio/Print 的本地化字符串。
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Twitter 的本地化字符串。
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must be less than 20 characters. 的本地化字符串。
        /// </summary>
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name is required. 的本地化字符串。
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Email 的本地化字符串。
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re almost done! Check your email. 的本地化字符串。
        /// </summary>
        public static string VerifyEmailInfo {
            get {
                return ResourceManager.GetString("VerifyEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check this link in the email we sent to 的本地化字符串。
        /// </summary>
        public static string VerifyEmailInfo1 {
            get {
                return ResourceManager.GetString("VerifyEmailInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to complete your account 的本地化字符串。
        /// </summary>
        public static string VerifyEmailInfo2 {
            get {
                return ResourceManager.GetString("VerifyEmailInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Videography&amp;Editing 的本地化字符串。
        /// </summary>
        public static string VideographyEditing {
            get {
                return ResourceManager.GetString("VideographyEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Assistant 的本地化字符串。
        /// </summary>
        public static string VirtualAssistant {
            get {
                return ResourceManager.GetString("VirtualAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I want to Hire 的本地化字符串。
        /// </summary>
        public static string WantHire {
            get {
                return ResourceManager.GetString("WantHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instant access to the world&apos;s top pool of rated contractors. 的本地化字符串。
        /// </summary>
        public static string WantHireInfo {
            get {
                return ResourceManager.GetString("WantHireInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Want Job 的本地化字符串。
        /// </summary>
        public static string WantJob {
            get {
                return ResourceManager.GetString("WantJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What Type of Jobs Do You Want? 的本地化字符串。
        /// </summary>
        public static string WantJobInfo1 {
            get {
                return ResourceManager.GetString("WantJobInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a category below. Don&apos;t worry, you can change your category or add more categories later if needed. 的本地化字符串。
        /// </summary>
        public static string WantJobInfo2 {
            get {
                return ResourceManager.GetString("WantJobInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes! Send me new job listing in the selected category. 的本地化字符串。
        /// </summary>
        public static string WantJobInfo3 {
            get {
                return ResourceManager.GetString("WantJobInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of Jobs You Want 的本地化字符串。
        /// </summary>
        public static string WantJobType {
            get {
                return ResourceManager.GetString("WantJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I want to Work 的本地化字符串。
        /// </summary>
        public static string WantWork {
            get {
                return ResourceManager.GetString("WantWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find clients, get hired, get paid 的本地化字符串。
        /// </summary>
        public static string WantWorkInfo {
            get {
                return ResourceManager.GetString("WantWorkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web Content 的本地化字符串。
        /// </summary>
        public static string WebContent {
            get {
                return ResourceManager.GetString("WebContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web Design 的本地化字符串。
        /// </summary>
        public static string WebDesign {
            get {
                return ResourceManager.GetString("WebDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web Programming 的本地化字符串。
        /// </summary>
        public static string WebProgramming {
            get {
                return ResourceManager.GetString("WebProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web Search Engine 的本地化字符串。
        /// </summary>
        public static string WebSearchEngine {
            get {
                return ResourceManager.GetString("WebSearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations! You&apos;re now registered. 的本地化字符串。
        /// </summary>
        public static string WelcomeInfo1 {
            get {
                return ResourceManager.GetString("WelcomeInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post a job to get proposals and hire contractors on Task publish system. 的本地化字符串。
        /// </summary>
        public static string WelcomeInfo2 {
            get {
                return ResourceManager.GetString("WelcomeInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worker Profile 的本地化字符串。
        /// </summary>
        public static string WorkerProfile {
            get {
                return ResourceManager.GetString("WorkerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing&amp;Translation 的本地化字符串。
        /// </summary>
        public static string WritingTranslation {
            get {
                return ResourceManager.GetString("WritingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zip/Postal Code 的本地化字符串。
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
