//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Internationalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test task..
        /// </summary>
        public static string AboutInfo {
            get {
                return ResourceManager.GetString("AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this task.
        /// </summary>
        public static string AboutTask {
            get {
                return ResourceManager.GetString("AboutTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address required..
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Support.
        /// </summary>
        public static string AdminSupport {
            get {
                return ResourceManager.GetString("AdminSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        public static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Development.
        /// </summary>
        public static string ApplicationDevelopment {
            get {
                return ResourceManager.GetString("ApplicationDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        public static string AreaCode {
            get {
                return ResourceManager.GetString("AreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Writing.
        /// </summary>
        public static string ArticleWriting {
            get {
                return ResourceManager.GetString("ArticleWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics Information.
        /// </summary>
        public static string BasicsInfo {
            get {
                return ResourceManager.GetString("BasicsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username exists, please try a different username..
        /// </summary>
        public static string CheckUser {
            get {
                return ResourceManager.GetString("CheckUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please chose the file!.
        /// </summary>
        public static string ChoseFile {
            get {
                return ResourceManager.GetString("ChoseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name(optional).
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference.
        /// </summary>
        public static string Conference {
            get {
                return ResourceManager.GetString("Conference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue &gt;&gt;.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Area Code.
        /// </summary>
        public static string CountryPhone {
            get {
                return ResourceManager.GetString("CountryPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coworker.
        /// </summary>
        public static string Coworker {
            get {
                return ResourceManager.GetString("Coworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello and welcome to Demo! Already have an account?.
        /// </summary>
        public static string CreateAccountInfo {
            get {
                return ResourceManager.GetString("CreateAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Basics Informations.
        /// </summary>
        public static string CreateBasics {
            get {
                return ResourceManager.GetString("CreateBasics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Your Profile Started!.
        /// </summary>
        public static string CreateBasicsInfo1 {
            get {
                return ResourceManager.GetString("CreateBasicsInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, let&apos;s get some basics out of the way....
        /// </summary>
        public static string CreateBasicsInfo2 {
            get {
                return ResourceManager.GetString("CreateBasicsInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Employer Informations.
        /// </summary>
        public static string CreateEmployer {
            get {
                return ResourceManager.GetString("CreateEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Skills Informations.
        /// </summary>
        public static string CreateSkills {
            get {
                return ResourceManager.GetString("CreateSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Your Profile Started!.
        /// </summary>
        public static string CreateSkillsInfo1 {
            get {
                return ResourceManager.GetString("CreateSkillsInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market your skills and experience....
        /// </summary>
        public static string CreateSkillsInfo2 {
            get {
                return ResourceManager.GetString("CreateSkillsInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Worker.
        /// </summary>
        public static string CreateWorker {
            get {
                return ResourceManager.GetString("CreateWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Contractor Account.
        /// </summary>
        public static string CreateWorkerInfo1 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking to hire?.
        /// </summary>
        public static string CreateWorkerInfo2 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Information.
        /// </summary>
        public static string CreateWorkerInfo3 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to represent yourself to clients on task publish system?.
        /// </summary>
        public static string CreateWorkerInfo4 {
            get {
                return ResourceManager.GetString("CreateWorkerInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        public static string DataEntry {
            get {
                return ResourceManager.GetString("DataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design&amp;Multimedia.
        /// </summary>
        public static string DesignMultimedia {
            get {
                return ResourceManager.GetString("DesignMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-books and Blogs.
        /// </summary>
        public static string EbooksBlogs {
            get {
                return ResourceManager.GetString("EbooksBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is not correct..
        /// </summary>
        public static string EmailFaield {
            get {
                return ResourceManager.GetString("EmailFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Information.
        /// </summary>
        public static string EmployerInfo {
            get {
                return ResourceManager.GetString("EmployerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Profile.
        /// </summary>
        public static string EmployerProfile {
            get {
                return ResourceManager.GetString("EmployerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name required..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Design.
        /// </summary>
        public static string GraphicDesign {
            get {
                return ResourceManager.GetString("GraphicDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My hourly rate.
        /// </summary>
        public static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be a number.
        /// </summary>
        public static string HourlyRateFailed {
            get {
                return ResourceManager.GetString("HourlyRateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My hourly rate required..
        /// </summary>
        public static string HourlyRateRequired {
            get {
                return ResourceManager.GetString("HourlyRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you hear about us?.
        /// </summary>
        public static string How {
            get {
                return ResourceManager.GetString("How", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustration.
        /// </summary>
        public static string Illustration {
            get {
                return ResourceManager.GetString("Illustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT&amp;Programming.
        /// </summary>
        public static string ITProgramming {
            get {
                return ResourceManager.GetString("ITProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageList.
        /// </summary>
        public static string LanguageAdd {
            get {
                return ResourceManager.GetString("LanguageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageList.
        /// </summary>
        public static string LanguageList {
            get {
                return ResourceManager.GetString("LanguageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageManage.
        /// </summary>
        public static string LanguageManage {
            get {
                return ResourceManager.GetString("LanguageManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name required..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Generation.
        /// </summary>
        public static string LeadGeneration {
            get {
                return ResourceManager.GetString("LeadGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedln.
        /// </summary>
        public static string Linkedln {
            get {
                return ResourceManager.GetString("Linkedln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, please check the username and password..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input username and password. if you do not have an account, please.
        /// </summary>
        public static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logos.
        /// </summary>
        public static string Logos {
            get {
                return ResourceManager.GetString("Logos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManageMainPage.
        /// </summary>
        public static string ManageMainPage {
            get {
                return ResourceManager.GetString("ManageMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagerProfile.
        /// </summary>
        public static string ManagerProfile {
            get {
                return ResourceManager.GetString("ManagerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Apps.
        /// </summary>
        public static string MobileApps {
            get {
                return ResourceManager.GetString("MobileApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online advertisement.
        /// </summary>
        public static string OnlineAdvertisement {
            get {
                return ResourceManager.GetString("OnlineAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online news article.
        /// </summary>
        public static string OnlineNewsArticle {
            get {
                return ResourceManager.GetString("OnlineNewsArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverView {
            get {
                return ResourceManager.GetString("OverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview required..
        /// </summary>
        public static string OverViewRequired {
            get {
                return ResourceManager.GetString("OverViewRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passwords do not match..
        /// </summary>
        public static string PassWordFaield {
            get {
                return ResourceManager.GetString("PassWordFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be a phone number.
        /// </summary>
        public static string PhoneNumberField {
            get {
                return ResourceManager.GetString("PhoneNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Picture(optional).
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a Job.
        /// </summary>
        public static string PostJob {
            get {
                return ResourceManager.GetString("PostJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a client.
        /// </summary>
        public static string RegisterEmployer {
            get {
                return ResourceManager.GetString("RegisterEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relemarketing.
        /// </summary>
        public static string Relemarketing {
            get {
                return ResourceManager.GetString("Relemarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        public static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend verification email.
        /// </summary>
        public static string ResendEmail {
            get {
                return ResourceManager.GetString("ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string RetypePassWord {
            get {
                return ResourceManager.GetString("RetypePassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password required..
        /// </summary>
        public static string RetypePassWordRequired {
            get {
                return ResourceManager.GetString("RetypePassWordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales&amp;Marketing.
        /// </summary>
        public static string SalesMarketing {
            get {
                return ResourceManager.GetString("SalesMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search&amp;Online Marketing.
        /// </summary>
        public static string SearchOnlineMarketing {
            get {
                return ResourceManager.GetString("SearchOnlineMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        public static string SelectALL {
            get {
                return ResourceManager.GetString("SelectALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Task publish system!.
        /// </summary>
        public static string SendEmailBody {
            get {
                return ResourceManager.GetString("SendEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, error happened, please wait!.
        /// </summary>
        public static string SendEmailFaield {
            get {
                return ResourceManager.GetString("SendEmailFaield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your E-mail address..
        /// </summary>
        public static string SendEmailSubject {
            get {
                return ResourceManager.GetString("SendEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are already send a E-mail to you, please check it and verify your E-mail address..
        /// </summary>
        public static string SendEmailSuccess {
            get {
                return ResourceManager.GetString("SendEmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills and Experience.
        /// </summary>
        public static string SkillsExperience {
            get {
                return ResourceManager.GetString("SkillsExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills required..
        /// </summary>
        public static string SkillsRequired {
            get {
                return ResourceManager.GetString("SkillsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media Site.
        /// </summary>
        public static string SocialMediaSite {
            get {
                return ResourceManager.GetString("SocialMediaSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Profile.
        /// </summary>
        public static string StartProfile {
            get {
                return ResourceManager.GetString("StartProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What system will change clients(after system fees).
        /// </summary>
        public static string SystemRate {
            get {
                return ResourceManager.GetString("SystemRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be a number.
        /// </summary>
        public static string SystemRateFailed {
            get {
                return ResourceManager.GetString("SystemRateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Rate required..
        /// </summary>
        public static string SystemRateRequired {
            get {
                return ResourceManager.GetString("SystemRateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks publish system.
        /// </summary>
        public static string SystemTitle {
            get {
                return ResourceManager.GetString("SystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagline(optional).
        /// </summary>
        public static string Tagline {
            get {
                return ResourceManager.GetString("Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription.
        /// </summary>
        public static string Transcription {
            get {
                return ResourceManager.GetString("Transcription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV/Radio/Print.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less than 20 characters..
        /// </summary>
        public static string UserNameMaxLength {
            get {
                return ResourceManager.GetString("UserNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Email.
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re almost done! Check your email..
        /// </summary>
        public static string VerifyEmailInfo {
            get {
                return ResourceManager.GetString("VerifyEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this link in the email we sent to.
        /// </summary>
        public static string VerifyEmailInfo1 {
            get {
                return ResourceManager.GetString("VerifyEmailInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to complete your account.
        /// </summary>
        public static string VerifyEmailInfo2 {
            get {
                return ResourceManager.GetString("VerifyEmailInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videography&amp;Editing.
        /// </summary>
        public static string VideographyEditing {
            get {
                return ResourceManager.GetString("VideographyEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Assistant.
        /// </summary>
        public static string VirtualAssistant {
            get {
                return ResourceManager.GetString("VirtualAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to Hire.
        /// </summary>
        public static string WantHire {
            get {
                return ResourceManager.GetString("WantHire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant access to the world&apos;s top pool of rated contractors..
        /// </summary>
        public static string WantHireInfo {
            get {
                return ResourceManager.GetString("WantHireInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want Job.
        /// </summary>
        public static string WantJob {
            get {
                return ResourceManager.GetString("WantJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Type of Jobs Do You Want?.
        /// </summary>
        public static string WantJobInfo1 {
            get {
                return ResourceManager.GetString("WantJobInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category below. Don&apos;t worry, you can change your category or add more categories later if needed..
        /// </summary>
        public static string WantJobInfo2 {
            get {
                return ResourceManager.GetString("WantJobInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes! Send me new job listing in the selected category..
        /// </summary>
        public static string WantJobInfo3 {
            get {
                return ResourceManager.GetString("WantJobInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Jobs You Want.
        /// </summary>
        public static string WantJobType {
            get {
                return ResourceManager.GetString("WantJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to Work.
        /// </summary>
        public static string WantWork {
            get {
                return ResourceManager.GetString("WantWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find clients, get hired, get paid.
        /// </summary>
        public static string WantWorkInfo {
            get {
                return ResourceManager.GetString("WantWorkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Content.
        /// </summary>
        public static string WebContent {
            get {
                return ResourceManager.GetString("WebContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Design.
        /// </summary>
        public static string WebDesign {
            get {
                return ResourceManager.GetString("WebDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Programming.
        /// </summary>
        public static string WebProgramming {
            get {
                return ResourceManager.GetString("WebProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Search Engine.
        /// </summary>
        public static string WebSearchEngine {
            get {
                return ResourceManager.GetString("WebSearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You&apos;re now registered..
        /// </summary>
        public static string WelcomeInfo1 {
            get {
                return ResourceManager.GetString("WelcomeInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a job to get proposals and hire contractors on Task publish system..
        /// </summary>
        public static string WelcomeInfo2 {
            get {
                return ResourceManager.GetString("WelcomeInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Profile.
        /// </summary>
        public static string WorkerProfile {
            get {
                return ResourceManager.GetString("WorkerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing&amp;Translation.
        /// </summary>
        public static string WritingTranslation {
            get {
                return ResourceManager.GetString("WritingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal Code.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
